#define         DEBUG           0
/***********************************************/
/***                                         ***/
/***                P C  DEFINE              ***/
/***                                         ***/
/***********************************************/
#define         COMM_SUCCESS    0
#define         COMM_FAIL       1
#define         RECEIVE_ERR     2
#define         TRANS_ERR       3
#define         TIME_ERR        4

#define         PGM_DOWN        1
#define         PGM_UP          2
#define         REP_UP          3
#define         REP_ZUP         4
#define         COMM_OFF        5

#define         MAX_CDATA       233

#define         DATA_DSTART     15
#define         DATA_USTART     17

#define         UD_DEPT         1
#define         UD_PLU          2
#define         UD_GROUP        3
#define         UD_SYS_OPT      4
#define         UD_PRT_OPT      5
#define         UD_FUNCKEY      6
#define         UD_TAX_TBL      7
#define         UD_CLERK        8
#define         UD_MESSDEC      9
#define         UD_TARE         10
#define         UD_STP          11
#define         UD_STD          12
#define         UD_DTM          13

#define         REP_FIN         1
#define         REP_DEPT        2
#define         REP_CLERK       3
#define         REP_TIME        4
#define         REP_DAY         5
#define         REP_GROUP       6
#define         REP_PLU         7
#define         REP_FIN2        8
#define         REP_STP         9
#define         REP_STD         10
#define         REP_EJ          11
#define         REP_CIO         12
#define         REP_DEPT2       13

